name: CI

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "README*.md"
      - "fastlane/**"
      - "assets/**"
      - ".github/**/*.md"

  schedule:
    - cron: '48 0 * * *'
      paths-ignore:
        - "README*.md"
        - "fastlane/**"
        - "assets/**"
        - ".github/**/*.md"

jobs:
  debug-builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "temurin"
          cache: "gradle"

      - name: Compile
        run: |
          ./gradlew assembleDebug

      - name: Sign Apk
        id: sign_apk
        uses: ilharp/sign-android-release@nightly
        with:
          releaseDir: app/build/outputs/apk/debug
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Rename signed APKs
        run: |
          mkdir -p signed
          while read -r file; do
            platform=$(echo "${file}" | sed -rn 's/(.*)app-(.+?)-debug-signed.apk$/\2/p')
            mv "${file}" "signed/libretube-${platform}-debug_${{ steps.date.outputs.date }}.apk"
          done <<< "$(echo "${ANDROID_SIGNED_FILES}" | tr ":" "\n")"

          echo "Renamed these files:"
          ls -1 signed/

      - name: Checkout nightly repo
        # if: github.event.schedule == '48 0 * * *'
        uses: actions/checkout@v4
        with:
          repository: jeidnx/nightly-test
          token: ${{ secrets.GH_TOKEN }}
          path: nightly

        
      - name: Create a new nightly tag
        run: |
          git tag ${{ steps.date.outputs.date }}
          git push --tags
          
      - name: Create nightly release
        # if: github.event.schedule == '48 0 * * *'
        uses: softprops/action-gh-release@v2
        with:
          repository: jeidnx/nightly-test
          name: LibreTube nightly ${{ steps.date.outputs.date }}
          tag_name: ${{ steps.date.outputs.date }}
          token: ${{ secrets.GH_TOKEN }}
          files: "signed/*.apk"
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: builds
          path: "signed/*.apk"

