name: Dispatch nightly builds

on:
  workflow_dispatch:
  schedule:
    - cron: '48 0 * * *'

jobs:
  dispatch_nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch nightly builds
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: jeidnx/nightly-test
          event-type: build-nightly
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
