name: Nightly builds

on:
  workflow_dispatch:
  schedule:
    - cron: '48 0 * * *'

jobs:
  nightly-builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "temurin"
          cache: "gradle"

      - name: Compile
        run: |
          ./gradlew assembleDebug assembleRelease

      - name: Move unsigned APKs
        run: |
          mkdir -p unsigned
          mv app/build/outputs/apk/debug/*.apk unsigned
          mv app/build/outputs/apk/release/*.apk unsigned

      - name: Sign APKs
        id: sign_apk
        # Switch to v2 when that is released, see https://github.com/ilharp/sign-android-release/issues/24#issuecomment-2414013354
        uses: ilharp/sign-android-release@nightly
        with:
          releaseDir: unsigned
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Get current date
        id: date
        # run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        #TODO: remove
        run: echo "date=2024-10-15" >> $GITHUB_OUTPUT

      - name: Rename signed APKs
        run: |
          mkdir -p signed
          while read -r file; do
            variant=$(echo "${file}" | sed -rn 's/(.*)app-(.+?)-(debug|release)(-unsigned)?-signed.apk$/\2-\3/p')
            mv "${file}" "signed/libretube-${variant}_${{ steps.date.outputs.date }}.apk"
          done <<< "$(echo "${ANDROID_SIGNED_FILES}" | tr ":" "\n")"

          echo "Renamed these files:"
          ls -1 signed/

      - name: Checkout nightly repo
        uses: actions/checkout@v4
        with:
          # repository: libre-tube/NightlyBuilds
          repository: jeidnx/nightly-test
          token: ${{ secrets.GH_TOKEN }}
          path: nightly
        
      - name: Update readme and push tag
        env:
          DATE: ${{ steps.date.outputs.date }}
        run: |
          cd nightly
          git config user.name "libretube-bot"
          git config user.email "libretube@proton.me"

          envsubst < readme_template.md > README.md
          envsubst < release_template.md > ~/release.md
          git add README.md
          git commit -m "update README.md"

          git tag ${{ steps.date.outputs.date }}
          git push --tags origin main
          
      - name: Create nightly release
        uses: softprops/action-gh-release@v2
        with:
          repository: jeidnx/nightly-test
          name: LibreTube nightly ${{ steps.date.outputs.date }}
          tag_name: ${{ steps.date.outputs.date }}
          body_path: ~/release.md
          token: ${{ secrets.GH_TOKEN }}
          files: "signed/*.apk"

